const ACERVO = [
  {
    id: "altair-8800", nome: "Altair 8800", fabricante: "MITS", ano: 1975, tipo: "computador", pais: "EUA",
    cpu: "Intel 8080 · 2 MHz", memoria: "256 bytes (padrão)", midia: "Chaves no painel frontal",
    perfil: "programar", brasil: false,
    descricao: "Vendido como kit de montar, não tinha tela nem teclado: o usuário programava bit a bit, movendo chaves e lendo luzes.",
    curiosidade: "Foi para ele que Bill Gates e Paul Allen escreveram o Altair BASIC, o primeiro produto da Microsoft.",
  },
  {
    id: "apple-ii", nome: "Apple II", fabricante: "Apple", ano: 1977, tipo: "computador", pais: "EUA",
    cpu: "MOS 6502 · 1 MHz", memoria: "4 KB a 48 KB", midia: "Fita cassete e disquete",
    perfil: "trabalho", brasil: false,
    descricao: "Um dos primeiros computadores pessoais prontos para usar, com gráficos coloridos e slots de expansão.",
    curiosidade: "O VisiCalc, a primeira planilha eletrônica popular, fez muita gente comprar um Apple II só para usar o programa.",
  },
  {
    id: "atari-2600", nome: "Atari 2600", fabricante: "Atari", ano: 1977, tipo: "console", pais: "EUA",
    cpu: "MOS 6507 · ~1,19 MHz", memoria: "128 bytes", midia: "Cartucho",
    perfil: "jogos", brasil: false,
    descricao: "O console que levou os videogames de cartucho para a sala de milhões de famílias.",
    curiosidade: "Com tão pouca memória, os programadores geravam a imagem linha a linha, em sincronia com o feixe da TV.",
  },
  {
    id: "ibm-pc-5150", nome: "IBM PC 5150", fabricante: "IBM", ano: 1981, tipo: "computador", pais: "EUA",
    cpu: "Intel 8088 · 4,77 MHz", memoria: "16 KB a 256 KB", midia: "Disquete de 5¼ pol.",
    perfil: "trabalho", brasil: false,
    descricao: "O computador que levou a informática para dentro dos escritórios e definiu o padrão dos PCs até hoje.",
    curiosidade: "Sua arquitetura aberta permitiu que outras empresas fabricassem clones compatíveis, o que moldou o mercado inteiro.",
  },
  {
    id: "commodore-64", nome: "Commodore 64", fabricante: "Commodore", ano: 1982, tipo: "computador", pais: "EUA",
    cpu: "MOS 6510 · ~1 MHz", memoria: "64 KB", midia: "Fita e disquete",
    perfil: "criar", brasil: false,
    descricao: "Barato, colorido e com um chip de som lendário, virou o computador doméstico de uma geração.",
    curiosidade: "Estimativas apontam entre 12 e 17 milhões de unidades vendidas, um dos micros mais vendidos da história.",
  },
  {
    id: "zx-spectrum", nome: "ZX Spectrum", fabricante: "Sinclair", ano: 1982, tipo: "computador", pais: "Reino Unido",
    cpu: "Zilog Z80A · 3,5 MHz", memoria: "16 KB ou 48 KB", midia: "Fita cassete",
    perfil: "programar", brasil: false,
    descricao: "Pequeno, barato e com teclado de borracha, abriu a programação para uma geração inteira de jovens britânicos.",
    curiosidade: "Os jogos vinham em fita e levavam alguns minutos para carregar, ao som estridente dos dados.",
  },
  {
    id: "macintosh-128k", nome: "Macintosh 128K", fabricante: "Apple", ano: 1984, tipo: "computador", pais: "EUA",
    cpu: "Motorola 68000 · ~7,83 MHz", memoria: "128 KB", midia: "Disquete de 3½ pol.",
    perfil: "criar", brasil: false,
    descricao: "O primeiro Mac popularizou a interface gráfica e o mouse, tudo em um gabinete compacto com tela de 9 polegadas.",
    curiosidade: "Foi apresentado ao mundo por um comercial de TV dirigido por Ridley Scott, exibido no Super Bowl de 1984.",
  },
  {
    id: "tk-90x", nome: "TK 90X", fabricante: "Microdigital", ano: 1985, tipo: "computador", pais: "Brasil",
    cpu: "Zilog Z80A · 3,5 MHz", memoria: "48 KB", midia: "Fita cassete",
    perfil: "programar", brasil: true,
    descricao: "Clone brasileiro do ZX Spectrum, foi a porta de entrada na programação para muita gente nos anos 80.",
    curiosidade: "Nasceu durante a reserva de mercado de informática, quando importar computadores era praticamente proibido.",
  },
  {
    id: "expert-msx", nome: "Gradiente Expert", fabricante: "Gradiente", ano: 1985, tipo: "computador", pais: "Brasil",
    cpu: "Zilog Z80A · 3,58 MHz", memoria: "64 KB", midia: "Cartucho e fita",
    perfil: "criar", brasil: true,
    descricao: "A versão brasileira do padrão MSX, que prometia que todo software rodaria em qualquer micro da família.",
    curiosidade: "O padrão MSX foi criado em 1983 por empresas japonesas e pela Microsoft para unificar os computadores domésticos.",
  },
  {
    id: "nes", nome: "NES (Famicom)", fabricante: "Nintendo", ano: 1985, tipo: "console", pais: "Japão",
    cpu: "Ricoh 2A03 · ~1,79 MHz", memoria: "2 KB", midia: "Cartucho",
    perfil: "jogos", brasil: false,
    descricao: "Lançado como Famicom no Japão em 1983, chegou ao Ocidente em 1985 e reergueu o mercado de videogames.",
    curiosidade: "O formato de leitura de cartucho, que entra de frente e desce, imitava um videocassete para não parecer um brinquedo.",
  },
  {
    id: "amiga-500", nome: "Amiga 500", fabricante: "Commodore", ano: 1987, tipo: "computador", pais: "EUA",
    cpu: "Motorola 68000 · ~7,09 MHz", memoria: "512 KB", midia: "Disquete de 3½ pol.",
    perfil: "criar", brasil: false,
    descricao: "Som estéreo de 4 canais e gráficos avançados para a época fizeram dele o queridinho de músicos e artistas digitais.",
    curiosidade: "Chips dedicados cuidavam de gráficos e som, deixando o processador livre para o resto do programa.",
  },
  {
    id: "mega-drive", nome: "Mega Drive", fabricante: "Sega", ano: 1988, tipo: "console", pais: "Japão",
    cpu: "Motorola 68000 · ~7,6 MHz", memoria: "64 KB", midia: "Cartucho",
    perfil: "jogos", brasil: false,
    descricao: "Console de 16 bits que bancou a rivalidade com a Nintendo e deu origem ao mascote Sonic.",
    curiosidade: "No Brasil foi lançado pela Tectoy a partir de 1990 e virou febre nas locadoras.",
  },
  {
    id: "game-boy", nome: "Game Boy", fabricante: "Nintendo", ano: 1989, tipo: "portatil", pais: "Japão",
    cpu: "Sharp LR35902 · ~4,19 MHz", memoria: "8 KB", midia: "Cartucho",
    perfil: "jogos", brasil: false,
    descricao: "Tela de 160×144 em quatro tons de verde e bateria que durava dezenas de horas: o portátil que ninguém derrubou.",
    curiosidade: "Veio com Tetris, e o jogo ajudou a levar o portátil para todas as idades.",
  },
  {
    id: "snes", nome: "Super Nintendo", fabricante: "Nintendo", ano: 1990, tipo: "console", pais: "Japão",
    cpu: "Ricoh 5A22 · até ~3,58 MHz", memoria: "128 KB", midia: "Cartucho",
    perfil: "jogos", brasil: false,
    descricao: "Cores vibrantes, som sampleado e o efeito Mode 7, que girava e inclinava o cenário.",
    curiosidade: "Super Mario World, que acompanhava o console, é até hoje citado entre os melhores jogos de plataforma.",
  },
  {
    id: "playstation", nome: "PlayStation", fabricante: "Sony", ano: 1994, tipo: "console", pais: "Japão",
    cpu: "MIPS R3000A · ~33,8 MHz", memoria: "2 MB", midia: "CD-ROM",
    perfil: "jogos", brasil: false,
    descricao: "Apostou no CD e no 3D poligonal, e transformou a Sony em potência dos videogames.",
    curiosidade: "Nasceu de uma parceria desfeita com a Nintendo, que planejava um acessório de CD para o Super Nintendo.",
  },
];

const EVENTOS = [
  { ano: 1975, titulo: "Nasce a Microsoft", texto: "Gates e Allen escrevem o BASIC do Altair 8800 e fundam a empresa.", maquina: "altair-8800" },
  { ano: 1977, titulo: "A trinca de 77", texto: "Apple II e Atari 2600 chegam ao mercado no mesmo ano e levam a tecnologia para dentro de casa.", maquina: "apple-ii" },
  { ano: 1979, titulo: "A planilha que vendeu computadores", texto: "O VisiCalc mostra que um micro pode ser ferramenta de trabalho.", maquina: null },
  { ano: 1981, titulo: "A IBM entra no jogo", texto: "O PC 5150 estabelece o padrão de arquitetura aberta que dura até hoje.", maquina: "ibm-pc-5150" },
  { ano: 1982, titulo: "O ano dos micros domésticos", texto: "Commodore 64 e ZX Spectrum popularizam o computador em casa.", maquina: "commodore-64" },
  { ano: 1984, titulo: "Chega o Macintosh", texto: "Interface gráfica e mouse chegam ao grande público.", maquina: "macintosh-128k" },
  { ano: 1985, titulo: "O micro brasileiro", texto: "Em plena reserva de mercado, surgem clones nacionais como o TK 90X e o Expert.", maquina: "tk-90x" },
  { ano: 1985, titulo: "Nintendo conquista o Ocidente", texto: "O NES chega aos Estados Unidos e reergue a indústria de games.", maquina: "nes" },
  { ano: 1987, titulo: "O Amiga encanta os criativos", texto: "O Amiga 500 une som e gráficos avançados a um preço acessível.", maquina: "amiga-500" },
  { ano: 1988, titulo: "A guerra dos 16 bits", texto: "Sega lança o Mega Drive e desafia a Nintendo.", maquina: "mega-drive" },
  { ano: 1989, titulo: "O portátil que virou ícone", texto: "O Game Boy leva os games para o bolso.", maquina: "game-boy" },
  { ano: 1990, titulo: "Super Nintendo", texto: "Chega o sucessor do NES, com Mode 7 e som sampleado.", maquina: "snes" },
  { ano: 1991, titulo: "Linus anuncia o Linux", texto: "Um estudante finlandês anuncia um sistema operacional livre.", maquina: null },
  { ano: 1994, titulo: "A era do CD e do 3D", texto: "O PlayStation populariza os jogos em CD-ROM com gráficos poligonais.", maquina: "playstation" },
  { ano: 1995, titulo: "Windows 95", texto: "O menu Iniciar e a barra de tarefas mudam a cara dos PCs.", maquina: null },
];
